#!/usr/bin/env python3
"""Flatten a CLAUDE.md tree into a single AGENTS.md.

    python3 scripts/flatten_claude_md.py --root . --out AGENTS.md

Claude Code resolves `@path` imports at read time. Other agents do not, so a CLAUDE.md
that imports three sub-files gives them three broken lines instead of the content. This
inlines every import in place, producing one self-contained file.

Exit codes:
    0  written
    1  something in the tree is wrong (missing import, cycle) - the file is not written
    2  the script could not run
"""

from __future__ import annotations

import argparse
import os
import re
import sys

# An @import line: leading whitespace, @, then a path. Anything else on the line means it
# is prose that happens to contain an @ (an email address, a decorator) and is left alone.
IMPORT_RE = re.compile(r"^\s*@([A-Za-z0-9_./-]+\.md)\s*$")

# Depth limit. A CLAUDE.md tree deeper than this is a structure problem, not an import
# problem, and following it further only produces an unreadable AGENTS.md.
MAX_DEPTH = 5

errors: list = []


def die(message: str) -> None:
    print("ERROR: {}".format(message), file=sys.stderr)
    sys.exit(2)


def inline(path: str, root: str, seen: list, depth: int) -> list:
    rel = os.path.relpath(path, root)
    if depth > MAX_DEPTH:
        errors.append("{}: import depth exceeds {}. Flatten the structure instead."
                      .format(rel, MAX_DEPTH))
        return []
    if path in seen:
        chain = " -> ".join(os.path.relpath(p, root) for p in seen + [path])
        errors.append("import cycle: {}".format(chain))
        return []

    try:
        with open(path, "r", encoding="utf-8") as handle:
            lines = handle.read().splitlines()
    except FileNotFoundError:
        errors.append("{}: imported but does not exist".format(rel))
        return []
    except OSError as exc:
        errors.append("{}: cannot read ({})".format(rel, exc))
        return []

    output = ["<!-- inlined from {} -->".format(rel)]
    for line in lines:
        match = IMPORT_RE.match(line)
        if not match:
            output.append(line)
            continue
        target = os.path.normpath(os.path.join(os.path.dirname(path), match.group(1)))
        output.append("")
        output.extend(inline(target, root, seen + [path], depth + 1))
        output.append("")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Flatten CLAUDE.md imports into AGENTS.md.")
    parser.add_argument("--root", default=".")
    parser.add_argument("--entry", default="CLAUDE.md")
    parser.add_argument("--out", default="AGENTS.md")
    args = parser.parse_args()

    root = os.path.abspath(args.root)
    if not os.path.isdir(root):
        die("--root {} is not a directory".format(root))

    entry = os.path.join(root, args.entry)
    if not os.path.isfile(entry):
        die("{} not found. Generate it first (dev-mentor Step 4).".format(entry))

    body = inline(entry, root, [], 0)
    if errors:
        for message in errors:
            print("  ERROR {}".format(message), file=sys.stderr)
        print("\n{} problem(s); {} not written.".format(len(errors), args.out),
              file=sys.stderr)
        return 1

    header = [
        "<!-- Generated by scripts/flatten_claude_md.py from {}.".format(args.entry),
        "     Edit the CLAUDE.md tree, then regenerate. Do not edit this file. -->",
        "",
    ]
    out_path = os.path.join(root, args.out) if not os.path.isabs(args.out) else args.out
    try:
        with open(out_path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(header + body).rstrip() + "\n")
    except OSError as exc:
        die("cannot write {}: {}".format(out_path, exc))

    print("Wrote {} ({} lines).".format(out_path, len(header) + len(body)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
